### ISSUE TITLE
windows-vuln-feed help 

### ISSUE THREAD

**Issue by externaldeveloper2** [vulsio/windows-vuln-feed#7]
Hey,

I would like to thank you so much for this amazing repo, My question is how can I Detect the missed KB in my computer 

Now I have your vulnerability Json, supersedence Json & I have the all installed KB on my computer, what is the next step and how can I detect which KB is missing in my computer? 

if you have a simple python code or any draft code can do it or any high level how you can use the collected KB from the computer & vulnerability Json, supersedence Json to how get the missed KB

**Comment by MaineK00n** [comment]
@externaldeveloper2 

missed KB does not mean unapplied KB, right?
Can you be more specific about the type of case you are looking for?

**Comment by externaldeveloper2** [comment]
Yes "missed KB does not mean unapplied KB, right?"

I need to get the unapplied KB (missed KB) 
for example, my windwos is up to date which means that I don't have any unapplied KB (no missed KB)

but if my windwos is out of date or I have unapplied kb


by using supersedence JSON KB how can I determine which KBs are unapplied?

**Comment by externaldeveloper2** [comment]
opps for this NO "missed KB does not mean unapplied KB, right?"


missed KB means the unapplied KB

**Comment by MaineK00n** [comment]
I will soon implement a feature at https://github.com/vulsio/gost that asks for a list of unapplied KBs from a list of applied KBs.

**Comment by MaineK00n** [comment]
You can use gost in this way to find the unapplied KB.
```console
$ gost version
gost v0.4.2 19488b9
$ gost fetch microsoft 
INFO[02-24|04:46:32] Initialize Database 
INFO[02-24|04:46:33] Fetched all CVEs from Microsoft 
INFO[02-24|04:46:35] Insert Microsoft CVEs into DB            db=sqlite3
INFO[02-24|04:46:35] Inserting cves                           cves=11609
11609 / 11609 [-------------------------------------------------------------------------------------] 100.00% 3894 p/s
INFO[02-24|04:46:38] Insert KB Relation                       relations=6016
6016 / 6016 [---------------------------------------------------------------------------------------] 100.00% 6815 p/s
$ gost server
INFO[02-24|04:46:46] Starting HTTP Server... 
INFO[02-24|04:46:46] Listening                                URL=127.0.0.1:1325

   ____    __
  / __/___/ /  ___
 / _// __/ _ \/ _ \
/___/\__/_//_/\___/ v3.3.10-dev
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
                                    O\
⇨ http server started on 127.0.0.1:1325

$ curl -H "Content-type: application/json" -X POST -d '{"applied": ["3194343"], "unapplied": ["4503327"]}' http://127.0.0.1:1325/microsoft/kbs | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   228  100   178  100    50  61485  17271 --:--:-- --:--:-- --:--:--  111k
{
  "applied": [
    "3194343"
  ],
  "unapplied": [
    "3202790",
    "3209498",
    "4018483",
    "4020821",
    "4512578",
    "4010250",
    "4507469",
    "4511553",
    "4503327",
    "3201860",
    "3214628",
    "4014329",
    "4022730",
    "4025376"
  ]
}
```
